### ISSUE TITLE
Pixel shift may  have unused code

### ISSUE THREAD

**Issue by tumuyan** [crabshank/HLSL-Reshade-colour-remappers#1]
https://github.com/crabshank/HLSL-Reshade-colour-remappers/blob/25fa27cbfbac8effc324664639226d494a444560/Pixel%20shift.hlsl#L15

Cause of `#define yInterval 0`， ` yInt=yInterval*one_over_height ` should always be set as 0?
and `ceny=(yInterval>0)?floor(tex.y/yInt)*yInt+(yInt*0.5):ceny;` never be true?

Actually I found that `#define one_over_width (p1[0]) ` in the MPC-BE hlsl template, but it's not clear how to use it. Then I searched it and found the variable that your repository . Do you have any idea?

**Comment by crabshank** [comment]
The problem is not with the code, but my lack of documentation: the `#define…` lines 15-20 are for the user to set as they want.

**Comment by tumuyan** [comment]
Ok .
Can you tell me does (p1[0])*(p0[0]) equal 1 ? or what does (p1[0]) mean?
Thanks

**Comment by crabshank** [comment]
#define width   (p0[0])
#define one_over_width  (p1[0])

Thus, `(p1[0])*(p0[0])=1`
